#! /usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

echo "------ JavaScript ------"
haxe build_js.hxml

echo "------ Python ------"
haxe build_python.hxml

# Java broken in ExpressionGroup.java
#echo "------ Java ------"
#haxe build_java.hxml
