#! /usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if [[ -f haxpression.zip ]]; then
  rm haxpression.zip
fi

./build
#git add -A
#git commit -m 'Submit to haxelib'

zip -r haxpression.zip LICENSE README.md build.hxml haxelib.json hmm.json src test

haxelib submit haxpression.zip
